default: &default
  adapter: postgresql
  encoding: unicode
  host: db # ローカルでrails serverを立ち上げる際はコメントアウトする
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: muscle_beat_development

test:
  <<: *default
  database: muscle_beat_test

production:
  <<: *default
  database: muscle_beat_production
  username: muscle_beat
  password: <%= ENV['MUSCLE_BEAT_DATABASE_PASSWORD'] %>
